/**
 * Answer generation module
 * 
 * IMPORTANT: Daily puzzles use the STATIC ANSWER_POOL below to ensure
 * all players get the same words on the same day.
 * 
 * Freeplay mode uses dynamically fetched words from the API for variety.
 */

// Re-export for freeplay mode (dynamic API words)
export { getRandomAnswers, initializeWordService } from './wordService';

// Static answer pool - NEVER CHANGE THE ORDER, only append new words at the end!
// This ensures daily puzzles remain consistent across all users and time.
export const ANSWER_POOL: string[] = [
  'ABROAD', 'ABSORB', 'ACCEPT', 'ACCESS', 'ACROSS', 'ACTION', 'ACTIVE', 'ACTUAL', 'ADVICE', 'AFFAIR',
  'AFFORD', 'AFRAID', 'AGENCY', 'ALMOST', 'ALWAYS', 'AMOUNT', 'ANIMAL', 'ANNUAL', 'ANSWER', 'ANYONE',
  'ANYWAY', 'APPEAL', 'APPEAR', 'AROUND', 'ARRIVE', 'ARTIST', 'ASKING', 'ASPECT', 'ATTACK', 'ATTEND',
  'AUTHOR', 'BANANA', 'BATTLE', 'BEAUTY', 'BECAME', 'BECOME', 'BEFORE', 'BEHALF', 'BEHIND', 'BELIEF',
  'BELONG', 'BETTER', 'BEYOND', 'BISHOP', 'BITTER', 'BORDER', 'BORROW', 'BOTTLE', 'BOTTOM', 'BOUGHT',
  'BOUNCE', 'BRANCH', 'BREATH', 'BRIDGE', 'BRIGHT', 'BRINGS', 'BROKEN', 'BRONZE', 'BUBBLE', 'BUDGET',
  'BURDEN', 'BUTTER', 'BUTTON', 'BUYING', 'CAMERA', 'CAMPUS', 'CANCEL', 'CANCER', 'CANDLE', 'CANNOT',
  'CARBON', 'CAREER', 'CARPET', 'CASTLE', 'CASUAL', 'CAUGHT', 'CAUSED', 'CENTER', 'CHANCE', 'CHANGE',
  'CHARGE', 'CHEESE', 'CHERRY', 'CHOICE', 'CHOOSE', 'CHOSEN', 'CHURCH', 'CIRCLE', 'CLIENT', 'CLOSED',
  'CLOSER', 'CLOUDS', 'COFFEE', 'COLUMN', 'COMBAT', 'COMING', 'COMMIT', 'COMMON', 'COPPER', 'CORNER',
  'COSTLY', 'COTTON', 'COUNTY', 'COUPLE', 'COURSE', 'CREATE', 'CREDIT', 'CRISIS', 'CUSTOM', 'DAMAGE',
  'DANCER', 'DANGER', 'DEALER', 'DEBATE', 'DECADE', 'DECIDE', 'DEFEAT', 'DEFEND', 'DEFINE', 'DEGREE',
  'DELETE', 'DEMAND', 'DENTAL', 'DEPEND', 'DEPUTY', 'DESERT', 'DESIGN', 'DESIRE', 'DETAIL', 'DETECT',
  'DEVICE', 'DIESEL', 'DIFFER', 'DINING', 'DINNER', 'DIRECT', 'DOCTOR', 'DOMAIN', 'DONATE', 'DOUBLE',
  'DRAGON', 'DRIVEN', 'DRIVER', 'DURING', 'EATING', 'EDITOR', 'EFFECT', 'EFFORT', 'EIGHTH', 'EITHER',
  'ELEVEN', 'EMERGE', 'EMPIRE', 'EMPLOY', 'ENABLE', 'ENDING', 'ENERGY', 'ENGAGE', 'ENGINE', 'ENOUGH',
  'ENSURE', 'ENTIRE', 'ENTITY', 'EQUITY', 'ESCAPE', 'ESTATE', 'ETHNIC', 'EVENTS', 'EVOLVE', 'EXCEED',
  'EXCEPT', 'EXCUSE', 'EXPAND', 'EXPECT', 'EXPERT', 'EXPORT', 'EXPOSE', 'EXTEND', 'EXTENT', 'FABRIC',
  'FACING', 'FACTOR', 'FAILED', 'FAIRLY', 'FALLEN', 'FAMILY', 'FAMOUS', 'FARMER', 'FASTER', 'FATHER',
  'FEMALE', 'FIELDS', 'FIERCE', 'FIGURE', 'FILLED', 'FILTER', 'FINALS', 'FINDER', 'FINGER', 'FINISH',
  'FLIGHT', 'FLOWER', 'FLYING', 'FOLDER', 'FOLLOW', 'FORCED', 'FOREST', 'FORGET', 'FORMAT', 'FORMER',
  'FOSSIL', 'FOSTER', 'FOUGHT', 'FOURTH', 'FRAMES', 'FREEZE', 'FRENCH', 'FRIDAY', 'FRIEND', 'FROZEN',
  'FUTURE', 'GALAXY', 'GAMING', 'GARAGE', 'GARDEN', 'GATHER', 'GENDER', 'GENTLE', 'GERMAN', 'GIFTED',
  'GIVING', 'GLOBAL', 'GOLDEN', 'GOTTEN', 'GOVERN', 'GRADES', 'GRANTS', 'GROUND', 'GROUPS', 'GROWTH',
  'GUARDS', 'GUESTS', 'GUITAR', 'HABITS', 'HAMMER', 'HANDED', 'HANDLE', 'HAPPEN', 'HARDLY', 'HAVING',
  'HEADED', 'HEADER', 'HEALTH', 'HEAVEN', 'HELPED', 'HIDDEN', 'HIGHER', 'HIGHLY', 'HIKING', 'HIRING',
  'HOLDER', 'HOLLOW', 'HONEST', 'HOPING', 'HORROR', 'HORSES', 'HOTELS', 'HOURLY', 'HOUSED', 'HOUSES',
  'HUMANS', 'HUMBLE', 'HUNGER', 'HUNTER', 'HYBRID', 'IGNORE', 'IMAGES', 'IMMUNE', 'IMPACT', 'IMPORT',
  'IMPOSE', 'INCOME', 'INDEED', 'INFANT', 'INFORM', 'INJURY', 'INPUTS', 'INSERT', 'INSIDE', 'INSIST',
  'INTACT', 'INTEND', 'INVEST', 'INVITE', 'ISLAND', 'ISSUED', 'JACKET', 'JERSEY', 'JUNGLE', 'JUNIOR',
  'KEEPER', 'KERNEL', 'KIDNEY', 'KILLED', 'KINDLE', 'KINDLY', 'KNIGHT', 'LABELS', 'LABOUR', 'LADIES',
  'LANDED', 'LAPTOP', 'LARGER', 'LASTLY', 'LATELY', 'LATEST', 'LAUNCH', 'LAWYER', 'LAYERS', 'LAYOUT',
  'LEADER', 'LEAGUE', 'LEAVES', 'LEGACY', 'LEGEND', 'LENGTH', 'LESSON', 'LETTER', 'LEVELS', 'LIGHTS',
  'LIKELY', 'LIMITS', 'LINEAR', 'LINKED', 'LIQUID', 'LISTED', 'LISTEN', 'LITTLE', 'LIVELY', 'LIVING',
  'LOADED', 'LOCALS', 'LOCATE', 'LOCKED', 'LOGGED', 'LONGER', 'LOSSES', 'LOVELY', 'LOWEST', 'LUXURY',
  'MAINLY', 'MAKING', 'MANAGE', 'MANNER', 'MANUAL', 'MARBLE', 'MARGIN', 'MARINE', 'MARKED', 'MARKER',
  'MARKET', 'MASTER', 'MATRIX', 'MATTER', 'MATURE', 'MEDIUM', 'MEMBER', 'MEMORY', 'MENTAL', 'MENTOR',
  'MERELY', 'METHOD', 'MIDDLE', 'MINING', 'MINUTE', 'MIRROR', 'MISSED', 'MOBILE', 'MODELS', 'MODERN',
  'MODEST', 'MODIFY', 'MODULE', 'MOMENT', 'MONDAY', 'MONTHS', 'MOTHER', 'MOTION', 'MOTORS', 'MOVING',
  'MURDER', 'MUSCLE', 'MUSEUM', 'MUTUAL', 'MYSELF', 'NAMELY', 'NARROW', 'NATION', 'NATIVE', 'NATURE',
  'NEARBY', 'NEARLY', 'NEEDED', 'NEWEST', 'NIGHTS', 'NOBODY', 'NORMAL', 'NOTICE', 'NOTION', 'NOVELS',
  'NUMBER', 'NURSES', 'OBJECT', 'OBTAIN', 'OCCUPY', 'OFFERS', 'OFFICE', 'OLDEST', 'ONLINE', 'OPENED',
  'OPENLY', 'OPTION', 'ORANGE', 'ORDERS', 'ORGANS', 'ORIGIN', 'OTHERS', 'OUTFIT', 'OUTPUT', 'OWNERS',
  'OXYGEN', 'PACKED', 'PALACE', 'PANELS', 'PAPERS', 'PARADE', 'PARENT', 'PARKED', 'PARTLY', 'PASSED',
  'PATENT', 'PAYING', 'PENCIL', 'PEOPLE', 'PEPPER', 'PERIOD', 'PERMIT', 'PERSON', 'PHONES', 'PHOTOS',
  'PHRASE', 'PICKED', 'PIECES', 'PILLOW', 'PIXELS', 'PLACED', 'PLACES', 'PLAINS', 'PLANET', 'PLANTS',
  'PLASMA', 'PLATES', 'PLAYER', 'PLEASE', 'PLENTY', 'POCKET', 'POETRY', 'POINTS', 'POLICE', 'POLICY',
  'POLISH', 'POORLY', 'PORTAL', 'POSTED', 'POSTER', 'POTATO', 'POUNDS', 'POWDER', 'POWERS', 'PRAYER',
  'PRETTY', 'PRICES', 'PRIEST', 'PRINCE', 'PRINTS', 'PRISON', 'PROFIT', 'PROMPT', 'PROPER', 'PROVEN',
  'PUBLIC', 'PULLED', 'PURPLE', 'PURSUE', 'PUSHED', 'PUZZLE', 'PYTHON', 'QUEENS', 'QUOTES', 'RABBIT',
  'RACING', 'RADIUS', 'RAISED', 'RANDOM', 'RANGES', 'RANKED', 'RARELY', 'RATHER', 'RATING', 'READER',
  'REALLY', 'REASON', 'REBELS', 'RECALL', 'RECENT', 'RECIPE', 'RECORD', 'REDUCE', 'REFORM', 'REFUSE',
  'REGARD', 'REGION', 'REJECT', 'RELATE', 'REMAIN', 'REMARK', 'REMIND', 'REMOTE', 'REMOVE', 'RENDER',
  'RENTAL', 'REPAIR', 'REPEAT', 'REPORT', 'RESCUE', 'RESIGN', 'RESIST', 'RESORT', 'RESULT', 'RESUME',
  'RETAIL', 'RETAIN', 'RETIRE', 'RETURN', 'REVEAL', 'REVIEW', 'REWARD', 'RIBBON', 'RIDING', 'RIGHTS',
  'RISING', 'RIVERS', 'ROBOTS', 'ROBUST', 'ROCKET', 'ROLLER', 'ROUTER', 'ROUTES', 'RUBBER', 'RULING',
  'RUNNER', 'SACRED', 'SAFARI', 'SAFELY', 'SAFETY', 'SAINTS', 'SALARY', 'SALMON', 'SAMPLE', 'SAVING',
  'SAYING', 'SCALES', 'SCARED', 'SCENES', 'SCHEME', 'SCHOOL', 'SCORES', 'SCREEN', 'SCRIPT', 'SCROLL',
  'SEARCH', 'SEASON', 'SECOND', 'SECRET', 'SECTOR', 'SECURE', 'SEEING', 'SEEKER', 'SELECT', 'SELLER',
  'SENATE', 'SENDER', 'SENIOR', 'SENSOR', 'SERIAL', 'SERIES', 'SERVER', 'SERVES', 'SETTLE', 'SEVERE',
  'SHADOW', 'SHAPED', 'SHAPES', 'SHARED', 'SHARES', 'SHELLS', 'SHIELD', 'SHIFTS', 'SHIRTS', 'SHOWED',
  'SHOWER', 'SIGNAL', 'SIGNED', 'SILENT', 'SILVER', 'SIMPLE', 'SIMPLY', 'SINGER', 'SINGLE', 'SISTER',
  'SKILLS', 'SLIDER', 'SLIGHT', 'SLOWLY', 'SMOOTH', 'SOCCER', 'SOCIAL', 'SOCKET', 'SOLELY', 'SOLVED',
  'SOUGHT', 'SOUNDS', 'SOURCE', 'SPACES', 'SPEAKS', 'SPEEDS', 'SPHERE', 'SPIDER', 'SPIRIT', 'SPOKEN',
  'SPORTS', 'SPREAD', 'SPRING', 'SQUARE', 'STABLE', 'STAGES', 'STAIRS', 'STAMPS', 'STANDS', 'STARTS',
  'STATED', 'STATES', 'STATUS', 'STEADY', 'STICKY', 'STOCKS', 'STOLEN', 'STONES', 'STORED', 'STORES',
  'STORMS', 'STRAIN', 'STRAND', 'STREAK', 'STREAM', 'STREET', 'STRESS', 'STRICT', 'STRIKE', 'STRING',
  'STRIPS', 'STROKE', 'STRONG', 'STRUCK', 'STUDIO', 'SUBMIT', 'SUBTLE', 'SUDDEN', 'SUFFER', 'SUITED',
  'SUMMER', 'SUMMIT', 'SUNDAY', 'SUNSET', 'SUPPLY', 'SURELY', 'SURVEY', 'SWITCH', 'SYMBOL', 'SYNTAX',
  'SYSTEM', 'TABLET', 'TACKLE', 'TALENT', 'TALKED', 'TARGET', 'TAUGHT', 'TENDER', 'TENNIS', 'THANKS',
  'THEORY', 'THINGS', 'THIRTY', 'THOUGH', 'THREAD', 'THREAT', 'THRONE', 'THROWN', 'TICKET', 'TIMBER',
  'TIMING', 'TISSUE', 'TITLES', 'TOILET', 'TOMATO', 'TONGUE', 'TOPICS', 'TOWARD', 'TOWERS', 'TRACES',
  'TRACKS', 'TRADER', 'TRADES', 'TRAGIC', 'TRAILS', 'TRAINS', 'TRAVEL', 'TREATY', 'TRENDS', 'TRIALS',
  'TRIBES', 'TRICKS', 'TRIPLE', 'TROOPS', 'TROPHY', 'TRUCKS', 'TRUSTS', 'TUNNEL', 'TURKEY', 'TURNED',
  'TURTLE', 'TWELVE', 'TWENTY', 'TYPING', 'UNABLE', 'UNFAIR', 'UNIQUE', 'UNITED', 'UNLESS', 'UNLIKE',
  'UNLOCK', 'UPDATE', 'UPLOAD', 'URGENT', 'USEFUL', 'VACANT', 'VACUUM', 'VALLEY', 'VALUED', 'VALUES',
  'VARIED', 'VECTOR', 'VENDOR', 'VENUES', 'VERBAL', 'VERIFY', 'VERSUS', 'VESSEL', 'VICTIM', 'VIDEOS',
  'VIEWED', 'VIEWER', 'VIOLIN', 'VIRTUE', 'VISION', 'VISUAL', 'VOICES', 'VOLUME', 'VOTERS', 'VOTING',
  'WAITED', 'WAITER', 'WALKED', 'WALLET', 'WANDER', 'WANTED', 'WARMTH', 'WARNED', 'WEALTH', 'WEAPON',
  'WEEKLY', 'WEIGHT', 'WHEELS', 'WHILST', 'WHITES', 'WIDELY', 'WIDGET', 'WILDLY', 'WINDOW', 'WINNER',
  'WINTER', 'WISDOM', 'WISHED', 'WISHES', 'WITHIN', 'WIZARD', 'WONDER', 'WOODEN', 'WORKER', 'WORTHY',
  'WOUNDS', 'WRITER', 'YEARLY', 'YELLOW', 'YOGURT', 'ZENITH', 'ZOMBIE',
];

/**
 * Seeded random number generator (mulberry32)
 * Used to ensure consistent daily puzzles across all users
 */
function seededRandom(seed: number): () => number {
  return function () {
    let t = seed += 0x6D2B79F5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

/**
 * Get answers for DAILY puzzles using the STATIC answer pool
 * This ensures all players get the same words on the same day
 */
export function getDailyAnswersFromPool(count: number, seed: number): string[] {
  const shuffled = [...ANSWER_POOL];
  const random = seededRandom(seed);

  // Fisher-Yates shuffle with seeded random
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }

  return shuffled.slice(0, count);
}
