// Curated subset list of 6-letter English words
export const VALID_WORDS: Set<string> = new Set([
  // A
  'ABROAD', 'ABSORB', 'ACCEPT', 'ACCESS', 'ACCORD', 'ACCUSE', 'ACROSS', 'ACTION', 'ACTIVE', 'ACTUAL',
  'ADVICE', 'ADVISE', 'AFFAIR', 'AFFECT', 'AFFORD', 'AFRAID', 'AGENCY', 'AGENDA', 'ALMOST', 'ALUMNI',
  'ALWAYS', 'AMOUNT', 'ANIMAL', 'ANNUAL', 'ANSWER', 'ANYONE', 'ANYWAY', 'APPEAL', 'APPEAR', 'AROUND',
  'ARRIVE', 'ARTIST', 'ASKING', 'ASPECT', 'ASSESS', 'ASSIST', 'ASSUME', 'ATTACK', 'ATTEND', 'AUTHOR',
  'AVENUE', 'BACKUP', 'BALANCE',
  // B
  'BANANA', 'BARELY', 'BATTLE', 'BEAUTY', 'BECAME', 'BECOME', 'BEFORE', 'BEHALF', 'BEHAVE', 'BEHIND',
  'BELIEF', 'BELONG', 'BESIDE', 'BETTER', 'BEYOND', 'BISHOP', 'BITTER', 'BLANKET', 'BORDER', 'BORROW',
  'BOTTLE', 'BOTTOM', 'BOUGHT', 'BOUNCE', 'BRANCH', 'BREATH', 'BRIDGE', 'BRIGHT', 'BRINGS', 'BROKEN',
  'BRONZE', 'BROTHER', 'BROWSE', 'BRUTAL', 'BUBBLE', 'BUDGET', 'BUFFER', 'BURDEN', 'BURIED', 'BUTTER',
  'BUTTON', 'BUYING',
  // C
  'CABIN', 'CABLES', 'CACHED', 'CAMERA', 'CAMPUS', 'CANCEL', 'CANCER', 'CANDLE', 'CANNOT', 'CANVAS',
  'CARBON', 'CAREER', 'CARPET', 'CASINO', 'CASTLE', 'CASUAL', 'CAUGHT', 'CAUSED', 'CAUSES', 'CEMENT',
  'CENTER', 'CENTRE', 'CHANCE', 'CHANGE', 'CHARGE', 'CHARTS', 'CHEESE', 'CHERRY', 'CHOICE', 'CHOOSE',
  'CHOSEN', 'CHURCH', 'CIRCLE', 'CLAIMS', 'CLAUSE', 'CLIENT', 'CLIMAT', 'CLOSED', 'CLOSER', 'CLOUDS',
  'CLUSTER', 'COFFEE', 'COLUMN', 'COMBAT', 'COMING', 'COMMIT', 'COMMON', 'COMPLY', 'CONFIG', 'COPPER',
  'CORNER', 'CORONA', 'COSTLY', 'COTTON', 'COUNTY', 'COUPLE', 'COURSE', 'COURTS', 'COVERS', 'CREATE',
  'CREDIT', 'CRISIS', 'CUSTOM', 'CYPHER',
  // D
  'DAMAGE', 'DANGER', 'DARWIN', 'DEALER', 'DEATHS', 'DEBATE', 'DECADE', 'DECIDE', 'DECREE', 'DEEMED',
  'DEEPLY', 'DEFEAT', 'DEFEND', 'DEFINE', 'DEGREE', 'DELETE', 'DEMAND', 'DENIAL', 'DENIED', 'DENTAL',
  'DEPEND', 'DEPLOY', 'DEPUTY', 'DERIVE', 'DESERT', 'DESIGN', 'DESIRE', 'DETAIL', 'DETECT', 'DEVICE',
  'DEVOTE', 'DIESEL', 'DIFFER', 'DINING', 'DINNER', 'DIRECT', 'DOCTOR', 'DOMAIN', 'DONATE', 'DOUBLE',
  'DOZENS', 'DRAGON', 'DRIVEN', 'DRIVER', 'DRIVES', 'DURING', 'DUTIES',
  // E
  'EATING', 'EDITOR', 'EFFECT', 'EFFORT', 'EIGHTH', 'EITHER', 'ELEVEN', 'EMERGE', 'EMPIRE', 'EMPLOY',
  'ENABLE', 'ENDING', 'ENERGY', 'ENGAGE', 'ENGINE', 'ENOUGH', 'ENSURE', 'ENTIRE', 'ENTITY', 'EQUITY',
  'ESCAPE', 'ESTATE', 'ETHNIC', 'EVENTS', 'EVOLVE', 'EXCEED', 'EXCEPT', 'EXCESS', 'EXCUSE', 'EXPAND',
  'EXPECT', 'EXPERT', 'EXPORT', 'EXPOSE', 'EXTEND', 'EXTENT', 'EXTRAS',
  // F
  'FABRIC', 'FACING', 'FACTOR', 'FAILED', 'FAIRLY', 'FALLEN', 'FAMILY', 'FAMOUS', 'FARMER', 'FASTER',
  'FATHER', 'FAVOUR', 'FEARED', 'FELLOW', 'FEMALE', 'FIELDS', 'FIERCE', 'FIGURE', 'FILING', 'FILLED',
  'FILTER', 'FINALS', 'FINDER', 'FINGER', 'FINISH', 'FISCAL', 'FISHER', 'FITTED', 'FIXING', 'FLAVOR',
  'FLIGHT', 'FLOORS', 'FLOWER', 'FLYING', 'FOLDED', 'FOLDER', 'FOLLOW', 'FORCED', 'FORCES', 'FOREST',
  'FORGET', 'FORMAT', 'FORMER', 'FORUMS', 'FOSSIL', 'FOSTER', 'FOUGHT', 'FOURTH', 'FRAMES', 'FREELY',
  'FREEZE', 'FRENCH', 'FRIDAY', 'FRIEND', 'FROZEN', 'FUTURE',
  // G
  'GALAXY', 'GAMBLE', 'GAMING', 'GARAGE', 'GARDEN', 'GATHER', 'GENDER', 'GENIUS', 'GENTLE', 'GERMAN',
  'GIFTED', 'GIVING', 'GLOBAL', 'GOLDEN', 'GOTTEN', 'GOVERN', 'GRADES', 'GRANTS', 'GRAPES', 'GRAPHS',
  'GRAVEL', 'GREEDY', 'GREENS', 'GRILL', 'GROOVE', 'GROUND', 'GROUPS', 'GROWTH', 'GUARDS', 'GUESTS',
  'GUITAR', 'GUIDED',
  // H
  'HABITS', 'HACKER', 'HAMMER', 'HANDED', 'HANDLE', 'HAPPEN', 'HARDLY', 'HAVING', 'HAZARD', 'HEADED',
  'HEADER', 'HEALTH', 'HEARTS', 'HEAVEN', 'HELPED', 'HELPER', 'HEREBY', 'HEROES', 'HIDDEN', 'HIGHER',
  'HIGHLY', 'HIKING', 'HIRING', 'HOLDER', 'HOLLOW', 'HONEST', 'HOPING', 'HORROR', 'HORSES', 'HOSTEL',
  'HOTELS', 'HOURLY', 'HOUSED', 'HOUSES', 'HUMANS', 'HUMBLE', 'HUNGER', 'HUNTER', 'HYBRID',
  // I
  'ICONIC', 'IDEALS', 'IGNORE', 'IMAGES', 'IMMUNE', 'IMPACT', 'IMPORT', 'IMPOSE', 'INCHES', 'INCOME',
  'INDEED', 'INDOOR', 'INFANT', 'INFORM', 'INJURY', 'INPUTS', 'INSERT', 'INSIDE', 'INSIST', 'INTACT',
  'INTAKE', 'INTEND', 'INTENT', 'INVEST', 'INVITE', 'INVOKE', 'ISLAND', 'ISSUED', 'ISSUES', 'ITSELF',
  // J
  'JACKET', 'JARGON', 'JERSEY', 'JOCKEY', 'JOKING', 'JORDAN', 'JOSEPH', 'JUNGLE', 'JUNIOR', 'JUSTLY',
  // K
  'KEEPER', 'KERNEL', 'KIDNEY', 'KILLED', 'KILLER', 'KINDLE', 'KINDLY', 'KNIGHT', 'KNIVES', 'KOREAN',
  // L
  'LABELS', 'LABOUR', 'LADIES', 'LAMBDA', 'LANDED', 'LAPTOP', 'LARGER', 'LASTLY', 'LATELY', 'LATEST',
  'LATTER', 'LAUNCH', 'LAWYER', 'LAYERS', 'LAYOUT', 'LEADER', 'LEAGUE', 'LEAVES', 'LEGACY', 'LEGEND',
  'LENDER', 'LENGTH', 'LESSON', 'LETTER', 'LEVELS', 'LIABLE', 'LIGHTS', 'LIKELY', 'LIMITS', 'LINEAR',
  'LINKED', 'LIQUID', 'LISTED', 'LISTEN', 'LITTLE', 'LIVELY', 'LIVING', 'LOADED', 'LOCALS', 'LOCATE',
  'LOCKED', 'LOGGED', 'LONGER', 'LOOKUP', 'LOSSES', 'LOVELY', 'LOVERS', 'LOWEST', 'LUXURY', 'LYRICS',
  // M
  'MADRID', 'MAINLY', 'MAKING', 'MANAGE', 'MANNER', 'MANUAL', 'MAPPED', 'MARBLE', 'MARGIN', 'MARINE',
  'MARKED', 'MARKER', 'MARKET', 'MASTER', 'MATRIX', 'MATTER', 'MATURE', 'MEDIUM', 'MEMBER', 'MEMORY',
  'MENTAL', 'MENTOR', 'MERELY', 'MERGER', 'METHOD', 'MIDDLE', 'MILLER', 'MINING', 'MINUTE', 'MIRROR',
  'MISSED', 'MOBILE', 'MODELS', 'MODERN', 'MODEST', 'MODIFY', 'MODULE', 'MOMENT', 'MONDAY', 'MONTHS',
  'MOTHER', 'MOTION', 'MOTORS', 'MOVING', 'MURDER', 'MUSCLE', 'MUSEUM', 'MUTUAL', 'MYSELF', 'MYSTIC',
  // N
  'NAMELY', 'NARROW', 'NATION', 'NATIVE', 'NATURE', 'NEARBY', 'NEARLY', 'NEATLY', 'NEEDED', 'NEEDLE',
  'NESTED', 'NEURAL', 'NEWEST', 'NICELY', 'NIGHTS', 'NOBODY', 'NORMAL', 'NOTICE', 'NOTION', 'NOVELS',
  'NUDITY', 'NUMBER', 'NURSES',
  // O
  'OBJECT', 'OBTAIN', 'OCCUPY', 'OCCURS', 'OFFERS', 'OFFICE', 'OFFSET', 'OLDEST', 'ONLINE', 'OPENED',
  'OPENLY', 'OPERAT', 'OPPOSE', 'OPTION', 'ORANGE', 'ORDERS', 'ORGANS', 'ORIENT', 'ORIGIN', 'OTHERS',
  'OUTFIT', 'OUTPUT', 'OWNERS', 'OXYGEN',
  // P
  'PACKED', 'PACKET', 'PALACE', 'PANELS', 'PAPERS', 'PARADE', 'PARENT', 'PARISH', 'PARKED', 'PARKER',
  'PARTLY', 'PASSED', 'PASSES', 'PASTOR', 'PATENT', 'PATROL', 'PATRON', 'PAYING', 'PENCIL', 'PEOPLE',
  'PEPPER', 'PERIOD', 'PERMIT', 'PERSON', 'PETROL', 'PHASES', 'PHONES', 'PHOTOS', 'PHRASE', 'PICKED',
  'PICKUP', 'PIECES', 'PILLOW', 'PILOTS', 'PIXELS', 'PLACED', 'PLACES', 'PLAINS', 'PLAINS', 'PLANET',
  'PLANTS', 'PLASMA', 'PLATES', 'PLAYER', 'PLEASE', 'PLEDGE', 'PLENTY', 'PLUGIN', 'POCKET', 'POETRY',
  'POINTS', 'POLICE', 'POLICY', 'POLISH', 'POLITE', 'POORLY', 'PORTAL', 'POSING', 'POSTED', 'POSTER',
  'POTATO', 'POUNDS', 'POWDER', 'POWERS', 'PRAYER', 'PREFIX', 'PRETTY', 'PRICES', 'PRIEST', 'PRINCE',
  'PRINTS', 'PRISON', 'PROFIT', 'PROMPT', 'PROPER', 'PROVEN', 'PUBLIC', 'PULLED', 'PURELY', 'PURPLE',
  'PURSUE', 'PUSHED', 'PUZZLE', 'PYTHON',
  // Q
  'QUARTZ', 'QUEENS', 'QUOTES', 'QUOTED', 'QUIVER', 'QUILTS',
  // R
  'RABBIT', 'RACING', 'RACISM', 'RACIAL', 'RADIAL', 'RADIUS', 'RAISED', 'RANDOM', 'RANGES', 'RANKED',
  'RAPIDS', 'RARELY', 'RATHER', 'RATING', 'READER', 'REALTY', 'REALLY', 'REASON', 'REBELS', 'RECALL',
  'RECENT', 'RECIPE', 'RECORD', 'RECTOR', 'REDUCE', 'REFERS', 'REFORM', 'REFUGE', 'REFUSE', 'REGARD',
  'REGIME', 'REGION', 'REJECT', 'RELATE', 'REMAIN', 'REMARK', 'REMEDY', 'REMIND', 'REMOTE', 'REMOVE',
  'RENDER', 'RENTAL', 'REPAIR', 'REPEAT', 'REPLAY', 'REPORT', 'RESCUE', 'RESIGN', 'RESIST', 'RESORT',
  'RESULT', 'RESUME', 'RETAIL', 'RETAIN', 'RETIRE', 'RETURN', 'REVEAL', 'REVIEW', 'REWARD', 'RHYTHM',
  'RIBBON', 'RICHLY', 'RIDING', 'RIGHTS', 'RISING', 'RIVERS', 'ROBOTS', 'ROBUST', 'ROCKET', 'ROLLER',
  'ROMANS', 'ROSTER', 'ROTATE', 'ROUTER', 'ROUTES', 'RUBBER', 'RULING', 'RUNNER', 'RUNWAY', 'RUSSIA',
  // S
  'SACRED', 'SADDLE', 'SAFARI', 'SAFELY', 'SAFETY', 'SAINTS', 'SALARY', 'SALMON', 'SAMPLE', 'SAVING',
  'SAYING', 'SCALES', 'SCARED', 'SCENES', 'SCHEME', 'SCHOOL', 'SCORES', 'SCREEN', 'SCRIPT', 'SCROLL',
  'SEALED', 'SEARCH', 'SEASON', 'SECOND', 'SECRET', 'SECTOR', 'SECURE', 'SEEING', 'SEEKER', 'SELECT',
  'SELLER', 'SENATE', 'SENDER', 'SENIOR', 'SENSOR', 'SERIAL', 'SERIES', 'SERVER', 'SERVES', 'SETTLE',
  'SEVERE', 'SHADOW', 'SHAPED', 'SHAPES', 'SHARED', 'SHARES', 'SHELLS', 'SHIELD', 'SHIFTS', 'SHIRTS',
  'SHOWED', 'SHOWER', 'SHRINE', 'SIGNAL', 'SIGNED', 'SILENT', 'SILVER', 'SIMPLE', 'SIMPLY', 'SINGER',
  'SINGLE', 'SISTER', 'SKILLS', 'SLEEVE', 'SLIDER', 'SLIGHT', 'SLOWLY', 'SMOOTH', 'SNACKS', 'SOCCER',
  'SOCIAL', 'SOCKET', 'SODIUM', 'SOLELY', 'SOLVED', 'SOLVER', 'SOUGHT', 'SOUNDS', 'SOURCE', 'SPACES',
  'SPARSE', 'SPEAKS', 'SPEEDS', 'SPHERE', 'SPIDER', 'SPIRIT', 'SPLASH', 'SPOKEN', 'SPORTS', 'SPREAD',
  'SPRING', 'SQUARE', 'STABLE', 'STAGES', 'STAIRS', 'STAKES', 'STAMPS', 'STANDS', 'STARTS', 'STATED',
  'STATES', 'STATUS', 'STEADY', 'STEREO', 'STICKY', 'STOCKS', 'STOLEN', 'STONES', 'STORED', 'STORES',
  'STORMS', 'STRAIN', 'STRAND', 'STREAK', 'STREAM', 'STREET', 'STRESS', 'STRICT', 'STRIKE', 'STRING',
  'STRIPS', 'STROKE', 'STRONG', 'STRUCK', 'STUDIO', 'STUPID', 'SUBMIT', 'SUBTLE', 'SUBURB', 'SUDDEN',
  'SUFFER', 'SUFFIX', 'SUITED', 'SUMMER', 'SUMMIT', 'SUNDAY', 'SUNSET', 'SUPPLY', 'SURELY', 'SURVEY',
  'SWITCH', 'SYMBOL', 'SYNTAX', 'SYSTEM',
  // T
  'TABLET', 'TACKLE', 'TALENT', 'TALKED', 'TALLER', 'TARGET', 'TAUGHT', 'TAYLOR', 'TENDER', 'TENNIS',
  'TERMED', 'THANKS', 'THEORY', 'THESIS', 'THINGS', 'THIRTY', 'THOUGH', 'THREAD', 'THREAT', 'THRILL',
  'THRONE', 'THROWN', 'TICKET', 'TIMBER', 'TIMING', 'TISSUE', 'TITLES', 'TOILET', 'TOMATO', 'TONGUE',
  'TOPICS', 'TOPPED', 'TOWARD', 'TOWERS', 'TRACES', 'TRACKS', 'TRADED', 'TRADER', 'TRADES', 'TRAGIC',
  'TRAILS', 'TRAINS', 'TRAVEL', 'TREATY', 'TRENDS', 'TRIALS', 'TRIBES', 'TRICKS', 'TRIPLE', 'TROOPS',
  'TROPHY', 'TRUCKS', 'TRUSTS', 'TUNNEL', 'TURKEY', 'TURNED', 'TURTLE', 'TWELVE', 'TWENTY', 'TYPING',
  // U
  'UBUNTU', 'ULTIMA', 'UNABLE', 'UNFAIR', 'UNIQUE', 'UNITED', 'UNLESS', 'UNLIKE', 'UNLOCK', 'UNSURE',
  'UNUSED', 'UPDATE', 'UPLOAD', 'UPWARD', 'URGENT', 'USEFUL', 'USELESS',
  // V
  'VACANT', 'VACUUM', 'VALLEY', 'VALUED', 'VALUES', 'VARIED', 'VARIES', 'VECTOR', 'VELVET', 'VENDOR',
  'VENICE', 'VENUES', 'VERBAL', 'VERIFY', 'VERSUS', 'VESSEL', 'VICTIM', 'VIDEOS', 'VIEWED', 'VIEWER',
  'VIOLIN', 'VIRGIN', 'VIRTUE', 'VISION', 'VISUAL', 'VOICES', 'VOLUME', 'VOTERS', 'VOTING',
  // W
  'WAITED', 'WAITER', 'WALKED', 'WALKER', 'WALLET', 'WANDER', 'WANTED', 'WARMTH', 'WARNED', 'WASHED',
  'WASHER', 'WEALTH', 'WEAPON', 'WEEKLY', 'WEIGHT', 'WELDED', 'WESTER', 'WHEELS', 'WHILST', 'WHISKY',
  'WHITES', 'WHOLLY', 'WICKED', 'WIDELY', 'WIDGET', 'WILDER', 'WILDLY', 'WILSON', 'WINDOW', 'WINNER',
  'WINTER', 'WISDOM', 'WISHED', 'WISHES', 'WITHIN', 'WIZARD', 'WONDER', 'WOODEN', 'WORKER', 'WORTHY',
  'WOUNDS', 'WRITER', 'WRITES', 'WRITTEN', 'WRONGS',
  // X
  'XAVIER',
  // Y
  'YEARLY', 'YELLOW', 'YIELDS', 'YOGURT', 'YONDER', 'YOUTHS',
  // Z
  'ZEALOT', 'ZENITH', 'ZEPHYR', 'ZOMBIE', 'ZONING',
]);

export function isValidWord(word: string): boolean {
  return VALID_WORDS.has(word.toUpperCase());
}

